#[derive(Clone, Debug)]
pub enum Layer {
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Ten,
    Eleven,
    Twelve,
    Thirteen,
    Fourteen,
    Fifteen,
    Sixteen,
    Seventeen,
    Eighteen,
    Nineteen,
    Twenty,
    TwentyOne,
    TwentyTwo,
    TwentyThree,
    TwentyFour,
    TwentyFive,
    TwentySix,
    TwentySeven,
    TwentyEight,
    TwentyNine,
    Thirty,
    ThirtyOne,
    OutOfRange,

}

impl From<Layer> for u8 {
    fn from(i: Layer) -> u8 {
        match i {
            Layer::Zero => 0,
            Layer::One => 1,
            Layer::Two => 2,
            Layer::Three => 3,
            Layer::Four => 4,
            Layer::Five => 5,
            Layer::Six => 6,
            Layer::Seven => 7,
            Layer::Eight => 8,
            Layer::Nine => 9,
            Layer::Ten => 10,
            Layer::Eleven => 11,
            Layer::Twelve => 12,
            Layer::Thirteen => 13,
            Layer::Fourteen => 14,
            Layer::Fifteen => 15,
            Layer::Sixteen => 16,
            Layer::Seventeen => 17,
            Layer::Eighteen => 18,
            Layer::Nineteen => 19,
            Layer::Twenty => 20,
            Layer::TwentyOne => 21,
            Layer::TwentyTwo => 22,
            Layer::TwentyThree => 23,
            Layer::TwentyFour => 24,
            Layer::TwentyFive => 25,
            Layer::TwentySix => 26,
            Layer::TwentySeven => 27,
            Layer::TwentyEight => 28,
            Layer::TwentyNine => 29,
            Layer::Thirty => 30,
            Layer::ThirtyOne => 31,
            Layer::OutOfRange => 255,
        }
    }
}

impl From<u8> for Layer {
    fn from(i: u8) -> Layer {
        match i {
            0 => Layer::Zero,
            1 => Layer::One,
            2 => Layer::Two,
            3 => Layer::Three,
            4 => Layer::Four,
            5 => Layer::Five,
            6 => Layer::Six,
            7 => Layer::Seven,
            8 => Layer::Eight,
            9 => Layer::Nine,
            10 => Layer::Ten,
            11 => Layer::Eleven,
            12 => Layer::Twelve,
            13 => Layer::Thirteen,
            14 => Layer::Fourteen,
            15 => Layer::Fifteen,
            16 => Layer::Sixteen,
            17 => Layer::Seventeen,
            18 => Layer::Eighteen,
            19 => Layer::Nineteen,
            20 => Layer::Twenty,
            21 => Layer::TwentyOne,
            22 => Layer::TwentyTwo,
            23 => Layer::TwentyThree,
            24 => Layer::TwentyFour,
            25 => Layer::TwentyFive,
            26 => Layer::TwentySix,
            27 => Layer::TwentySeven,
            28 => Layer::TwentyEight,
            29 => Layer::TwentyNine,
            30 => Layer::Thirty,
            31 => Layer::ThirtyOne,
            _ => Layer::OutOfRange,
        }
    }
}

impl From<usize> for Layer {
    fn from(i: usize) -> Layer {
        match i {
            0 => Layer::Zero,
            1 => Layer::One,
            2 => Layer::Two,
            3 => Layer::Three,
            4 => Layer::Four,
            5 => Layer::Five,
            6 => Layer::Six,
            7 => Layer::Seven,
            8 => Layer::Eight,
            9 => Layer::Nine,
            10 => Layer::Ten,
            11 => Layer::Eleven,
            12 => Layer::Twelve,
            13 => Layer::Thirteen,
            14 => Layer::Fourteen,
            15 => Layer::Fifteen,
            16 => Layer::Sixteen,
            17 => Layer::Seventeen,
            18 => Layer::Eighteen,
            19 => Layer::Nineteen,
            20 => Layer::Twenty,
            21 => Layer::TwentyOne,
            22 => Layer::TwentyTwo,
            23 => Layer::TwentyThree,
            24 => Layer::TwentyFour,
            25 => Layer::TwentyFive,
            26 => Layer::TwentySix,
            27 => Layer::TwentySeven,
            28 => Layer::TwentyEight,
            29 => Layer::TwentyNine,
            30 => Layer::Thirty,
            31 => Layer::ThirtyOne,
            _ => Layer::OutOfRange,
        }
    }
}